os: linux
#required for arch different than amd64
dist: xenial
#language
language: python
python:
  - "3.8"
#cache installation
cache: pip
#python version

#Install pip dependencies
install:
  - "pip install -r requirements.txt"
  - "pip install coveralls"
#scripts to run on heroku

script:
  - python manage.py collectstatic --no-input
  - python manage.py makemigrations
  - python manage.py migrate
branches:
  only:
    - postgres
#run code coverage after scripts run successfully
# get token url from coveralls
# add webhooks as well
after_success:
  - coverage run manage.py test
  - coveralls
after_failure:
  - echo "Deployment failed"
 #deploy
deploy:
  provider: heroku
  cleanup: true
  strategy: git
  api_key:
    secure: oVrIEuwv39FiJMyVCtKKPHa6pD0Bi+j4/b3H7ass0H+1cLzNvjDyrHU9eN4lZtfhujcR7bOhD9xP0z5vt35j9z3RoUOOBCyaqM2Z8MaM2GU59oRefME/alVRrcsDtse3ran92AIyYIlPxZhmRLUK1p+4dHNezdoCnObmjAwkbX6FDvG/4NclgcFiCvu6Z27xTUHBVkgpFC2W+bhOrM3Ny0cPVJuoWCIzkQh2G4S0e+jzVOR2FodQ5FsQjaT9e1pSIgMv2f6U/0jk/fmsLCEtgdEUdNUgnqwky7qU1m2MSJw3c6toeQBRlGFKvPpwXUkckiFQZCP3if+l2AnLn9GX8ggfo8uor0kgUhKv0XOk3FY6oCJnZEE+dKmgpoznLfLEgSf+Jo8UQAnnJNK9SuffXbfPCfZlN+S9rOO7U9zbbBHTxnRWIYmSBW4CNcidr/S9O5gEyQ6pY46tqxZUyoLDkswdJEwHvZ4bZfJ7PtqiKFNc+jJY+Cfgr5XZMYSwTq8Z45ZmsJyoT8WXVbt1EFdDXkrzbmfpyQzcSU0PLlbC8YLTPzwXqFhvCBl5W5rwDeC5wd54dzLECGASTegcFRLBddqkH4SNoI/aa4qFL/xHTzuouCYKayBUYHZ/GP1I9LhbcvSLNnoS5VdFFuX4DnkFG1uBU4z9X3LeUaZ4CzR5Yto=
  # django app name
  app: pollcreator
  #branch name
  on: postgres
# Travis lifecycle
# before_install
# install
# after_install
# before_script
# script
# after_script
# after_success or after_failure
