os: linux
dist: xenial
language: python
python:
- '3.8'
cache: pip
install:
- pip install -r requirements.txt
- pip install coveralls
script:
- python manage.py collectstatic --no-input
- python manage.py makemigrations
- python manage.py migrate
branches:
  only:
  - postgres
after_success:
- coverage run manage.py test
- coveralls
after_failure:
- echo "Deployment failed"
deploy:
  provider: heroku
  cleanup: true
  strategy: git
  api_key:
    secure: cfq/sH2ye71JtVVur3Vo71qoGIHN0OrCq8NvQi3VyG0QfO21iVjVtZ9LCU3tCMvXoz/rktANNEz6K3c3XZjreabzmrqd+cCYPSV4rDFjNfzkzkwktxh+lnqL7Fe8fFTSap9gE+vwL5Uff4C/4OLPKd85uUIw4oD96YKcIikPnn0PETpeNkcttOexX+oEvCb3UOK7bvrGCBqkGxEF40VH2TF+4HoxjAOVRFCiZf20tQLCYGMkYxTrIpPI8i3hCwGIu9GX4jLCG8HukzT5tlD/9ID6Fbt0fTA7OBTpYLqrTYxhi1I74zwRzutCwc3TFbcLn9ku+p1gXEDgeL49Ilpwrg3IomHbZjV0hZUCCR3iGLXDsdyKRGtEGpxEcfuFJVPelnufkKO4mStvk6EH/QZq7lqy68TIPPyitOmQoju027d7BJkzZdzzMYztoBnQ8jg5iWYphMnVxZ1Chg6N+tfYdxLfxs0jlLSFJ96lRPMGeRKXmQk/+5dWvS3SL2xlmsGlu+DJLazL6uoZidG+jaxMn8+9pEQtVRzb5p3r/9FGH1tjPZ5MUUVZ/ueGJJLl5MtPK+87PT7f8gT8k9aRcsYLvyoY2HRxMLQRS6CmevY0NjijiiFzt2UktNJfwi7nbUWAJGMzmV5lEGnNHEcTvrJYBvx3iGkrTIqeJRhdx7WnLKM=
  app: pollcreator
  on: postgres
