# Generated by Django 3.1.1 on 2020-09-08 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollchoices',
            name='choice_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='poll',
            name='question_image',
            field=models.ImageField(default=None, upload_to=''),
        ),
    ]
