# Generated by Django 3.1.1 on 2020-09-08 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20200908_0740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='question_image',
            field=models.ImageField(blank=True, default=None, upload_to=''),
        ),
        migrations.AlterField(
            model_name='pollchoices',
            name='choice_image',
            field=models.ImageField(blank=True, default=None, upload_to=''),
        ),
    ]
