# Generated by Django 3.1.1 on 2020-09-08 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20200908_0748'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PollChoices',
            new_name='Choices',
        ),
    ]
