# Generated by Django 3.1.1 on 2020-09-09 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20200909_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='question_image',
            field=models.ImageField(blank=True, default=None, upload_to='question_image'),
        ),
    ]
