# Generated by Django 3.1.1 on 2020-09-09 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_auto_20200909_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='choice_image',
            field=models.ImageField(blank=True, upload_to='choice_image'),
        ),
    ]
